# Generated by Django 5.0 on 2023-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=100)),
                ('Writer_Name', models.CharField(max_length=100)),
                ('Serial_No', models.CharField(max_length=100)),
                ('Acquisition_Date', models.CharField(max_length=100)),
                ('Return_Date', models.CharField(max_length=100)),
                ('myImage', models.ImageField(null=True, upload_to='media/profile_pic')),
            ],
        ),
    ]
